### ISSUE TITLE
How to add or modify radio stations to actions.py

### ISSUE THREAD

**Issue by copmd** [shivasiddharth/Assistants-Pi#10]
I have tried to modify 'Radio 5' to 'Radio 4' with the same link, but it does not work.  Do I need to do additional actions to make it work?  The same with adding new entry/links.  Does not work.  Need help.  Thanks.

**Comment by shivasiddharth** [comment]
Please take a look at this ! https://youtu.be/ae0iwJ62uaM?t=622 i have explained as to why i have named Radio stations thus.

**Comment by copmd** [comment]
Thanks Sid.  That was helpful.
