### ISSUE TITLE
Step 9 ?

### ISSUE THREAD

**Issue by alexapi07** [shivasiddharth/Assistants-Pi#125]
I dont the know the step 9: "After verification of the assistants, to make them auto start on boot:
Pi 3 and Pi2 users, open the gassistpi-ok-google.service in the /home/pi/Assistants-Pi/systemd folder and add your project-id and model-id in the indicated points."What are indicated points?
What i shuold have to do with step 10 ?.

**Comment by ViharDevalla** [comment]
If you want to use GassistPi, open gassistpi-ok-google.service then add device-model-id at end of ExecStart line under [Service].
step 10 is for Alexa authorization to your Amazon acoount
