### ISSUE TITLE
Kodi control

### ISSUE THREAD

**Issue by iristvproject** [shivasiddharth/Assistants-Pi#13]
Sir, I'm not installed this on my rpi 3b but before starting I want to confirm whether I can control kodi using Google assistant in this build. And if yes, what are the few examples that I can try? 

Thanks in advance.

**Comment by shivasiddharth** [comment]
This build supports Kodi control. Please take a look at this README doc for syntax.:https://github.com/shivasiddharth/GassistPi

**Comment by iristvproject** [comment]
After installation completed while checking the demo app we encountered few problems. 
1. Companion service worked but javavlient didn't run... It says mvn is not found. 
2. Google model id error, I copied from model id file and pasted but it says its wrong. 

Any advice?
