### ISSUE TITLE
Alexa and Google both answering my question

### ISSUE THREAD

**Issue by MrPestle** [shivasiddharth/Assistants-Pi#133]
If I ask Google a question it gives the answer.
If I ask Alexa a question she answers but at almost the same time Google is also answering the question??? 
Also how can I set the google voice to be male all the time. I can ask it to change but on reboot it's back to female voice?
Any help gratefully received
Thanks for this great piece of work - loving it.
[28-01-2020.log](https://github.com/shivasiddharth/Assistants-Pi/files/4122241/28-01-2020.log)

**Comment by Arunkumar2712** [comment]
Pls tell what is you used in raspberry pi noods or raspbian os pls tell me I finish till last step the sample is not running in Google assistant so Iam asking

**Comment by MrPestle** [comment]
Running latest version of raspbian stretch. Solved my problem I think. I
was running two Google services, the single project and the combined
project.

**Comment by shivasiddharth** [comment]
closing this
