### ISSUE TITLE
Volume control for Google Voice HAT

### ISSUE THREAD

**Issue by TedMichalik** [shivasiddharth/Assistants-Pi#15]
I have both Alexa and the Google Assistant running on the Google Voice kit. The volume of the Alexa response is twice as loud as that of the Google Assistant. I tried lowering the volume in the Raspbian desktop, but that also lowered the Google Assistant volume to a barely audible level. Is there a way to adjust the volume of either assistant that is independent of the other?

**Comment by shivasiddharth** [comment]
Alexa's volume is managed by VLC. open a vlc player, reduce the volume and restart alexa, hopefully that should have some effect.

**Comment by jabulonboaz** [comment]
I had the same issue and fixed it by lowering the volume at the preferences and then asked google to “hey google volume maximum”. Now both assistants are at the same level.
