### ISSUE TITLE
cant perform step 10

### ISSUE THREAD

**Issue by sushant96702** [shivasiddharth/Assistants-Pi#170]
while executing command 
sudo /home/pi/Assistants-Pi/Alexa/startsample.sh  
it gave me error 
sudo: /home/pi/Assistants-Pi/Alexa/startsample.sh: command not found
startsample.sh is not there in alexa folder

**Comment by shivasiddharth** [comment]
The assistant has not been compiled properly. Re-run the installer.

**Comment by sushant96702** [comment]
> The assistant has not been compiled properly. Re-run the installer.

i reran but still same error

**Comment by shivasiddharth** [comment]
Manually open the Alexa folder and see if startsample.sh file is there or not. You need to watch the terminal. There might have been some compilation error. Just Re-running the installer will not fix any compilation issue, its not some magic step/command.

**Comment by sushant96702** [comment]
bro i checked all files it was not there : /

**Comment by shivasiddharth** [comment]
So its a compilation issue. You need to run the installer and watch for errors. If its not compiling properly it will for sure point out the error.

**Comment by kashifabidi** [comment]
> So its a compilation issue. You need to run the installer and watch for errors. If its not compiling properly it will for sure point out the error.

These are the only errors faced through install


chmod: cannot access '/home/root/Assistants-Pi/audio-drivers/USB-MIC-HDMI/scripts/configure.sh': No such file or directory
sudo: /home/root/Assistants-Pi/audio-drivers/USB-MIC-HDMI/scripts/configure.sh: command not found
chmod: cannot access '/home/root/Assistants-Pi/audio-drivers/USB-MIC-HDMI/scripts/install-usb-mic-hdmi.sh': No such file or directory
sudo: /home/root/Assistants-Pi/audio-drivers/USB-MIC-HDMI/scripts/install-usb-mic-hdmi.sh: command not found
Audio set to be forced through HDMI.

**Comment by kashifabidi** [comment]
Looking at OP's repository, the file isn't even on GIT

**Comment by kashifabidi** [comment]
> while executing command sudo /home/pi/Assistants-Pi/Alexa/startsample.sh it gave me error sudo: /home/pi/Assistants-Pi/Alexa/startsample.sh: command not found startsample.sh is not there in alexa folder


https://github.com/alexa/avs-device-sdk/issues/1003#issuecomment-536204106

Found this link somewhere, I am trying it now. Hope it helps us both.
