### ISSUE TITLE
Alexa not playing Music

### ISSUE THREAD

**Issue by Prasanna-16** [shivasiddharth/Assistants-Pi#171]
Hi sir. Everything in alexa works perfectly. But when I ask alexa to play music it says, " Music and radio playback are not supported on this device".
Please Help sir.

**Comment by Prasanna-16** [comment]
Sir also while installing alexa,
At last it said,
some tests did not run. Like media player test 16.. 
Finished insalling alexa.
Like that.

**Comment by shivasiddharth** [comment]
I cannot do anything about media playback. Amazon controls all those features. Please go through official documentation as to whats supported and whats not.

**Comment by Prasanna-16** [comment]
Ok sir
