### ISSUE TITLE
Custom Wakeword

### ISSUE THREAD

**Issue by iristvproject** [shivasiddharth/Assistants-Pi#18]
Sir, first of all i want to thank you for your fantastic works. I have tried to install Alexa and Google Assistant together using the instructions, but i don't know what went wrong but nothing worked. I've tried six times on fresh installed Raspbian and i was disappointed.
But later i tried to install alexa avs sample app seperately and it worked without any problems. Then without uninstalling anything, i tried to install google assistant, and it also worked!! Now I'm able to run both without any issues. 

But my only concern is i can change alexa's wakeword, but not google assistant's. So i want to know whether an update to this will come in near future so that i can change wakewords of both to my custom words.

Thanks in advance.

**Comment by jabulonboaz** [comment]
I would like to know this too, good question. Also if I have already set up evrithing can I customise the wakeword after and how please?
Again fantastic work, great project Sid. Thanks
