### ISSUE TITLE
[Question] Is it possible to add Alexa while Gassistpi is allready istalled?

### ISSUE THREAD

**Issue by siggi60** [shivasiddharth/Assistants-Pi#19]
Hi shivasiddharth,
first a big thanks to your awesome work.

I installed gassistpi and all is running fine. Now i was thinking about installing Alexa too.
Is that possible to add Alexa allone or do i have to install both?

Best regards
Siggi

**Comment by shivasiddharth** [comment]
The installer will give you an option to install both or either. So if you already have GasisstPi running, you can choose to install Alexa alone.
