### ISSUE TITLE
Package missing for Java install

### ISSUE THREAD

**Issue by TedMichalik** [shivasiddharth/Assistants-Pi#21]
The default Raspbian is missing package "dirmngr". This needs to be installed by install-java8.sh to keep the script from failing.

**Comment by shivasiddharth** [comment]
That is only if you are using a lite version. If you are running the desktop version, then you should not have any issue.

**Comment by TedMichalik** [comment]
I am running the desktop version. They must have changed it.

**Comment by nitinchauhan83** [comment]
I had similar issue

**Comment by shivasiddharth** [comment]
I have update the git with all the necessary fixes for Java installation.
