### ISSUE TITLE
Error while run google assistant demo

### ISSUE THREAD

**Issue by SarathKannan** [shivasiddharth/Assistants-Pi#24]
Hi shivasiddharth..

The following error has been occurred while run google assistant demo in new terminal ( i install only google assistant)

Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-hotword", line 7, in <module>
    from googlesamples.assistant.library.hotword import main
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/library/hotword.py",
line 27, in <module>
    from google.assistant.library import Assistant
ImportError: No module named 'google.assistant.library'

**Comment by shivasiddharth** [comment]
Not quite sure as to which guide you are following. The google assistant demo no longer works after the 20th Dec SDK update.
