### ISSUE TITLE
google assistant demo not working

### ISSUE THREAD

**Issue by PavanSN** [shivasiddharth/Assistants-Pi#25]
i've opened a new terminal and typed this

                                 source env/bin/activate

after that:

(env) pi@raspberrypi:~ $ googlesamples-assistant-hotword --project_id beebombot-193106 --device_model_id beebombot-193106-20180127112614
bash: googlesamples-assistant-hotword: command not found

whats the problem...

**Comment by shivasiddharth** [comment]
You have got the syntax wrong. your ids should be within single quotes. Eg: 'beebombot-193106' Pls check the systemd files.
