### ISSUE TITLE
headphone mic not working...

### ISSUE THREAD

**Issue by Kishu18** [shivasiddharth/Assistants-Pi#26]
HI Sid ..... I am trying to use my headphone mic with the program but it is not working.....even at the time of installation the mic didn't work....please help me out.....

**Comment by Rooster69** [comment]
Hi Kishu18, If you are using Bluetooth, you will have a very tough time trying to get it to work. I was in the same boat and gave up.

**Comment by Kishu18** [comment]
Thanks Rooster69 .......Problem Solved...

**Comment by shivasiddharth** [comment]
Closing this issue then !
