### ISSUE TITLE
voice recording test doesn't record the sound....

### ISSUE THREAD

**Issue by Kishu18** [shivasiddharth/Assistants-Pi#31]
it says 'arecord: main:788: audio open error: Device or resource busy

Finished recording the samples.

Playing back the recorded audio sample......

/home/pi/mic-test.wav: No such file or directory
Did you hear the recorded audio sample?
[y/n] >> n
Execute arecord -l in terminal and verify the card id with the ones mentioned in asound.conf file and .asoundrc file. Exiting...

**Comment by shivasiddharth** [comment]
Did you check your audio files as indicated?

**Comment by Kishu18** [comment]
Yes they were same.....

**Comment by shivasiddharth** [comment]
What is your audio setup ? attach your .asoundrc and asound.conf files here.
