### ISSUE TITLE
Alexa token not displayed on Web page ..... 

### ISSUE THREAD

**Issue by Kishu18** [shivasiddharth/Assistants-Pi#36]
it says page is not safe.....when i disable my antivirus it says error retrival of code....please fix this problem

**Comment by shivasiddharth** [comment]
It is not an issue and it is not because of your anti-virus. It appears because, you are visiting a less secure site. You need to choose "proceed anyway" and continue further.

**Comment by Kishu18** [comment]
I tried that too but it does not display the code....what can i do
