### ISSUE TITLE
Disable original hotwords

### ISSUE THREAD

**Issue by cherokee93** [shivasiddharth/Assistants-Pi#4]
Is there a way to change the hotword and disable "hey alexa" & "ok google" ? 
Because I'm getting too many false positives, I've tried to play with kitt.ai but it doesn't disable the original hotword.

**Comment by shivasiddharth** [comment]
Hotwords for alexa must be changed before installation for best results. Ok google cannot be changed, instead i have included a custom wakeword service that uses gRPC modules. Due to google's server issues its not working properly rit now..

**Comment by owenm95** [comment]
Hey. What is the customer wake word

**Comment by shivasiddharth** [comment]
Custom wakewords are snowboy and jarvis
