### ISSUE TITLE
assistants do not wake up to the hot words

### ISSUE THREAD

**Issue by Kishu18** [shivasiddharth/Assistants-Pi#43]

**Comment by Kishu18** [comment]
pi@raspberrypi:~ $ googlesamples-assistant-hotword --project_id anirudh-bot195 --device_model_id Anirudh
bash: googlesamples-assistant-hotword: command not found

**Comment by shivasiddharth** [comment]
Duplicate of #39 and #25. I had already warned and you dont seem to listen.
