### ISSUE TITLE
Google assistant service not detecting wakeword

### ISSUE THREAD

**Issue by baljagat** [shivasiddharth/Assistants-Pi#45]
Dear sid , 
Thanks for this project, it was very nice learning experience. 
There is one problem with me , google assistant service is running ok but wake word ok google is not detected . 
Meanwhilr alexa is working fine

**Comment by shivasiddharth** [comment]
What board are you using? and also please attach the log file, which can be found in the /tmp directory.

**Comment by baljagat** [comment]
Hi Shiva , 
I was able to run both simultaneously may be it was some isaue with installation. Just a clean install and things are running smooth , 
Thank you very much for such a great project 👍
