### ISSUE TITLE
Alexa & Google Assistant should not respond to hot word when talking!

### ISSUE THREAD

**Issue by cnoorman** [shivasiddharth/Assistants-Pi#46]
Hot word detection keeps on listening for "Alexa" or "Hey Google" when Alexa or GA are talking.
Especially Alexa quite often speaks her own name in her reaction to a questions and consequently triggers the next conversation before the current one is finished. This can bring her in an infinite loop, repeating the reaction till she arrives at her own name again, etc.
During conversation the hot word detection should be disabled to avoid this.

**Comment by shivasiddharth** [comment]
WIP to move to the Alexa SDK. Alexa will be much better with lesser hassles.
