### ISSUE TITLE
Manual Start of Google Assistant gives "No module named 'google.assistant.library'

### ISSUE THREAD

**Issue by rutherb** [shivasiddharth/Assistants-Pi#49]
Hi Shiva,

I have followed the correct instructions for the post December 20th installation from this link https://github.com/shivasiddharth/Assistants-Pi#readme but when I try to start the Google Assistant manually using the /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --project_id 'replace this with your project id'  --device_model_id 'replace this with the model id' command I get an error as below:-

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 29, in <module>
    from google.assistant.library import Assistant
ImportError: No module named 'google.assistant.library'

Can you help please?

**Comment by shadowscott** [comment]
I had this same problem. I had to follow instructions here, however @shivasiddharth mentioned that this is not the way to do it. I would like to know why it isn't installed as part of the scripts either. 

https://github.com/googlesamples/assistant-sdk-python

**Comment by rutherb** [comment]
Thanks for the info shadowscott - I will refresh Raspbian and follow above instructions and post update.

**Comment by shadowscott** [comment]
Sure thing. I will say that I reinstalled Raspbian and installed the google assistant from GassistPi instead. That worked flawlessly without hitch. I'm now trying to get Alexa installed as well (either through AssistantPi which hasn't worked, or maybe AlexaPi or some other method)

If you manage to get both working on the Google AIY Voice Kit, please let me know!!!

**Comment by nicusorflorin** [comment]
any updates on this?, have the same problem

**Comment by rutherb** [comment]
Hi - i upgraded to a later Raspberry Pi and reinstalled the Google assistant using these instructions https://github.com/googlesamples/assistant-sdk-python and it installed OK so I think it may have been the version of the PI I was using that caused the issue.
