### ISSUE TITLE
Import psutil

### ISSUE THREAD

**Issue by rmrozinsky** [shivasiddharth/Assistants-Pi#51]
I am having difficulty overcoming the ImportError: No module named 'psutil' issue. This is similar to #37, but following the guidance I am still encountering the error.

I am using a Raspberry Pi 3 running Stretch. Alexa is working, Google Assistant demo works. However, when I run:

pi@raspberrypi:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id HomeAssistantRPi
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 25, in <module>
    import psutil
ImportError: No module named 'psutil'

I get the specified import error. I installed the following modules under pi@raspberrypi:~ $ source env/bin/activate:
pip install psutil
pip install gmusicapi
pip install googletrans
pip install gtts
pip install pafy
pip install pychromecast

I again ran:

pi@raspberrypi:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id HomeAssistantRPi
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 25, in <module>
    import psutil
ImportError: No module named 'psutil'

encountering the same error.

I noted the following when pip install psutil the second time:

(env) pi@raspberrypi:~ $ pip install psutil
Requirement already satisfied: psutil in ./env/lib/python3.4/site-packages

Given Stretch is 3.5, I copied psutil and psutil 5.4.3. dist-info file folders from /home/pi/env/lib/python3.4/site-packages
to
/home/pi/env/lib/python3.5/site-packages

I re-ran:
pi@raspberrypi:~ $ /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id HomeAssistantRPi
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 25, in <module>
    import psutil
  File "/home/pi/env/lib/python3.5/site-packages/psutil/__init__.py", line 100, in <module>
    from . import _pslinux as _psplatform
  File "/home/pi/env/lib/python3.5/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux'

and encounter the specified error above.

I think I'm on the correct track, but looking for any direction on how to get the proper files in
/home/pi/env/lib/python3.5/site-packages
or any other insights on what is causing the error.

Thanks

**Comment by shivasiddharth** [comment]
You cannot just like that copy folders, it does not work. Can you confirm if you have multiple python versions in the environment ?
