### ISSUE TITLE
getting a kodi error?

### ISSUE THREAD

**Issue by Albiorix2016** [shivasiddharth/Assistants-Pi#53]
` /home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id ....
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 17, in <module>
    from kodijson import Kodi, PLAYER_VIDEO
ImportError: No module named 'kodijson'
`

get that error when i run the main.py

**Comment by shivasiddharth** [comment]
can you check if /env/python/library/site-packages has the kodi package?
