### ISSUE TITLE
Couple of issues....alexa installation over vnc (and desktop) gives errors and cant start google because of no /bin/activate directory

### ISSUE THREAD

**Issue by mazcoder** [shivasiddharth/Assistants-Pi#56]
This is an awesome project.  Your work is really appreciated and I can wait to get it all running! 

I am running rpi 3 model b v1.2 with rasbian stretch.

First issue is that I get errors with installing alexa when I am on vnc only. If I ssh and do the install and authentication it works (haven't tried the loading from boot sections yet but I can at least get alexa talking/responding). If I run
`sudo /home/pi/Assistants-Pi/installer.sh`
From vnc I get 
`[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 197 source files to /home/pi/alexa-avs-sample-app/samples/javaclient/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.474 s
[INFO] Finished at: 2018-04-14T21:10:06+00:00
[INFO] Final Memory: 10M/25M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project sample-java-client: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
========== Installing Companion Service ==========`

And over ssh I get
`[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.038 s
[INFO] Finished at: 2018-04-14T22:04:19+00:00
[INFO] Final Memory: 20M/82M
[INFO] ------------------------------------------------------------------------`

Issue number 2 is that I can't get google working at all. 
`pi@raspberrypi:~ $ source env/bin/activate
-bash: env/bin/activate: No such file or directory`

Any help would be greatly appreciated. Thanks!

**Comment by juantinoco** [comment]
In my case Alexa is working but I have the same problem with google...
