### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by v1n0ds** [shivasiddharth/Assistants-Pi#57]
@shivasiddharth After cloning the latest files, everything went fine until executing the last step which ended up showing **Build Failure**
Below are error messages

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project sample-java-client: /home/pi/alexa-avs-sample-app/samples/javaclient/target/classes/res/version.properties (Permission denied) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Please help as i'm using it to build my project.
Thanks

**Comment by badsmoke** [comment]
same issue
