### ISSUE TITLE
test.sh command not found

### ISSUE THREAD

**Issue by Shane-Lester** [shivasiddharth/Assistants-Pi#72]
```
========================Testing Alexa Installation========================
sudo: ./test.sh: command not found
========================Finished Installing Amazon Alexa========================
```
Assumed it would work due to the Finished Installing line (but noted the ./test.sh command not found
Followed the systemctl methods (using a Pi3)
When it came to step 10
`sudo /home/pi/Assistants-Pi/Alexa/startsample.sh ` 
I get the following
`sudo: /home/pi/Assistants-Pi/Alexa/startsample.sh: command not found`
Here's the contents of the Alexa directory
`alexa.sh  pi.sh  setup.sh`
and in the ~ directory there isn't a test.sh script

**Comment by shivasiddharth** [comment]
test.sh and startsample.sh will be created by the Alexa installer only if the compilation went through successfully. Looks like there was some issue in compilation. Are you using the latest version of the Raspbian Stretch OS ?

**Comment by Shane-Lester** [comment]
I was using a June version (but updated) so downloaded the latest and did a clean install- still no test.sh when setting up Alexa

**Comment by shivasiddharth** [comment]
If there is a problem with the credentials, then it will go through the installation, but will not authenticate. Sometimes, due to some network error, the installation would crash halfway through. You will see some warnings in red letters. You really need to watch the terminal and see as to whats going wrong. I know its a hard thing to do considering the amount of time alexa takes to setup.

**Comment by Shane-Lester** [comment]
I think it was a credentials problem but it failed quietly, clearing the screen without showing the error messages in about 3 minutes (I had been watching).
So I ran (using CMDER on Windows so I could use Unix type redirection)
`sudo /home/pi/Assistants-Pi/scripts/installer.sh  >> text.txt`
which exposed this message
`E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.`

So I ran the command and corrected the credentials and it's now running ... fingers crossed.

**Comment by shivasiddharth** [comment]
If the setup goes through successfully,  rename the existing project folder to something else, clone the master again and copy the files from newly cloned master into the old directory and name it back again. Last evening I added  startup and trigger audio tones and indicator  for Alexa.  
That would be missing in your old project folder.

**Comment by Shane-Lester** [comment]
I recloned and re-ran
Some failed tests - do I need to do anything
```96% tests passed, 35 tests failed out of 920

Total Test time (real) = 342.18 sec

The following tests FAILED:
        846 - MediaPlayerTest.testStartPlayWaitForEnd (Failed)
        847 - MediaPlayerTest.testStartPlayForUrl (Failed)
        848 - MediaPlayerTest.testConsecutiveSetSource (Failed)
        849 - MediaPlayerTest.testStartPlayWaitForEndStartPlayAgain (Failed)
        850 - MediaPlayerTest.testStopPlay (Failed)
        851 - MediaPlayerTest.testStartPlayCallAfterStopPlay (Failed)
        852 - MediaPlayerTest.testStartPlayCallAfterStopPlayDifferentSource (Failed)
        853 - MediaPlayerTest.testPauseDuringPlay (Failed)
        854 - MediaPlayerTest.testResumeAfterPauseThenStop (Failed)
        855 - MediaPlayerTest.testStopAfterPause (Failed)
        856 - MediaPlayerTest.testPauseAfterPause (Failed)
        857 - MediaPlayerTest.testResumeAfterPlay (Failed)
        858 - MediaPlayerTest.testGetOffsetInMilliseconds (Failed)
        860 - MediaPlayerTest.testGetOffsetWhenStoppedFails (Failed)
        861 - MediaPlayerTest.testGetOffsetWhenPaused (Failed)
        862 - MediaPlayerTest.testPlayingTwoAttachments (Failed)
        863 - MediaPlayerTest.testUnsteadyReads (Failed)
        864 - MediaPlayerTest.testRecoveryFromPausedReads (Failed)
        865 - MediaPlayerTest.testStartPlayWithUrlPlaylistWaitForEnd (Failed)
        866 - MediaPlayerTest.testSetOffsetSeekableSource (Failed)
        869 - MediaPlayerTest.testRepeatAttachment (Failed)
        870 - MediaPlayerTest.testSetVolumePlays (Failed)
        871 - MediaPlayerTest.testAdjustVolumePlaysDuringPlay (Failed)
        872 - MediaPlayerTest.testAdjustVolumePlays (Failed)
        873 - MediaPlayerTest.testAdjustVolumeOutOfBounds (Failed)
        874 - MediaPlayerTest.testSetMutePlays (Failed)
        877 - MediaPlayerTest.testReadTags (Failed)
        878 - MediaPlayerTest.testConsecutiveSameApiCalls (Failed)
        879 - MediaPlayerTest.testImmediatePause (Failed)
        880 - MediaPlayerTest.multiplePlayAndSetSource (Failed)
        882 - MediaPlayerTest.doublePause (Failed)
        883 - MediaPlayerTest.resumeWhenPlaying (Failed)
        884 - MediaPlayerTest.resumeWhenStopped (Failed)
        885 - MediaPlayerTest.newSetSourceLeadsToStoppedCallback (Failed)
        886 - MediaPlayerTest.resumeAfterPauseWithPendingPlay (Failed)
Errors while running CTest
Makefile:116: recipe for target 'test' failed
make: *** [test] Error 8```

**Comment by Shane-Lester** [comment]
And when trying to authorize Alexa

```
 $ sudo /home/pi/Assistants-Pi/Alexa/startsample.sh
2018-10-15 22:29:38.213 [  1] I sdkVersion: 1.9.0
configFile /home/pi/Assistants-Pi/Alexa/build/Integration/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2018-10-15 22:29:38.275 [  1] 0 ConfigurationNode:initializeSuccess
2018-10-15 22:29:38.287 [  1] 9 MediaPlayer:createCalled
2018-10-15 22:29:38.336 [  1] E MediaPlayer:setupPipelineFailed:reason=createAudioSinkElementFailed,audioSinkElement=alsasink
2018-10-15 22:29:38.336 [  1] E MediaPlayer:initPlayerFailed:reason=setupPipelineFailed
2018-10-15 22:29:38.337 [  1] 9 MediaPlayer:~MediaPlayerCalled

(SampleApp:13961): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
2018-10-15 22:29:38.337 [  1] 9 MediaPlayer:resetPipeline

(SampleApp:13961): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
2018-10-15 22:29:38.338 [  1] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=SpeakMediaPlayer
2018-10-15 22:29:38.338 [  1] C SampleApplication:Failed to create media player for speech!
2018-10-15 22:29:38.338 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!
```

**Comment by shivasiddharth** [comment]
How did you enter the clientid and product id ? Did you enter it within quotes or justed pasted it as such ?

**Comment by Shane-Lester** [comment]
Copy pasted - no quotes. Does it need quotes?

**Comment by shivasiddharth** [comment]
Thats fine. The client id should be from security profiles and then other devices and platforms

**Comment by shivasiddharth** [comment]
Do we have an update on the status of the errors ?

**Comment by Shane-Lester** [comment]
I've done a clean install of raspbian stretch lite and repeated the process (again just option 2 install Alexa).
Still have to run dos2linux
`pi.sh: line 35: pip: command not found`
So I checked and pip isn't installed. Installing now....

**Comment by shivasiddharth** [comment]
Just something hit me.. Are you using Pi Zero ?

**Comment by Shane-Lester** [comment]
Pi3.
Currently building well.

Currently only errors are:
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
FATALDoxygen is required to generate documentation.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Shane-Lester** [comment]
I saved the original Cient ID as detailed in your file, but checked it against the one in "Security Profiles" "Other Platforms and Devices" and it's the same.
The Product ID I get from the "Information" tab

**Comment by Shane-Lester** [comment]
Lots of failed MediaPlayerTest's
```
96% tests passed, 35 tests failed out of 920                                                                           │
                                                                                                                       │
Total Test time (real) = 323.84 sec                                                                                    │
                                                                                                                       │
The following tests FAILED:                                                                                            │
        846 - MediaPlayerTest.testStartPlayWaitForEnd (Failed)                                                         │
        847 - MediaPlayerTest.testStartPlayForUrl (Failed)                                                             │
        848 - MediaPlayerTest.testConsecutiveSetSource (Failed)                                                        │
        849 - MediaPlayerTest.testStartPlayWaitForEndStartPlayAgain (Failed)                                           │
        850 - MediaPlayerTest.testStopPlay (Failed)                                                                    │
        851 - MediaPlayerTest.testStartPlayCallAfterStopPlay (Failed)                                                  │
        852 - MediaPlayerTest.testStartPlayCallAfterStopPlayDifferentSource (Failed)                                   │
        853 - MediaPlayerTest.testPauseDuringPlay (Failed)                                                             │
        854 - MediaPlayerTest.testResumeAfterPauseThenStop (Failed)                                                    │
        855 - MediaPlayerTest.testStopAfterPause (Failed)                                                              │
        856 - MediaPlayerTest.testPauseAfterPause (Failed)                                                             │
        857 - MediaPlayerTest.testResumeAfterPlay (Failed)                                                             │
        858 - MediaPlayerTest.testGetOffsetInMilliseconds (Failed)                                                     │
        860 - MediaPlayerTest.testGetOffsetWhenStoppedFails (Failed)                                                   │
        861 - MediaPlayerTest.testGetOffsetWhenPaused (Failed)                                                         │
        862 - MediaPlayerTest.testPlayingTwoAttachments (Failed)                                                       │
        863 - MediaPlayerTest.testUnsteadyReads (Failed)                                                               │
        864 - MediaPlayerTest.testRecoveryFromPausedReads (Failed)                                                     │
        865 - MediaPlayerTest.testStartPlayWithUrlPlaylistWaitForEnd (Failed)                                          │
        866 - MediaPlayerTest.testSetOffsetSeekableSource (Failed)                                                     │
        869 - MediaPlayerTest.testRepeatAttachment (Failed)                                                            │
        870 - MediaPlayerTest.testSetVolumePlays (Failed)                                                              │
        871 - MediaPlayerTest.testAdjustVolumePlaysDuringPlay (Failed)                                                 │
        872 - MediaPlayerTest.testAdjustVolumePlays (Failed)                                                           │
        873 - MediaPlayerTest.testAdjustVolumeOutOfBounds (Failed)                                                     │
        874 - MediaPlayerTest.testSetMutePlays (Failed)                                                                │
        877 - MediaPlayerTest.testReadTags (Failed)                                                                    │
        878 - MediaPlayerTest.testConsecutiveSameApiCalls (Failed)                                                     │
        879 - MediaPlayerTest.testImmediatePause (Failed)                                                              │
        880 - MediaPlayerTest.multiplePlayAndSetSource (Failed)                                                        │
        882 - MediaPlayerTest.doublePause (Failed)                                                                     │
        883 - MediaPlayerTest.resumeWhenPlaying (Failed)                                                               │
        884 - MediaPlayerTest.resumeWhenStopped (Failed)                                                               │
        885 - MediaPlayerTest.newSetSourceLeadsToStoppedCallback (Failed)                                              │
        886 - MediaPlayerTest.resumeAfterPauseWithPendingPlay (Failed)                                                 │
Errors while running CTest                                                                                             │
Makefile:116: recipe for target 'test' failed                                                                          │
make: *** [test] Error 8                                                                                               │
========================Finished Installing Amazon Alexa========================
```

**Comment by shivasiddharth** [comment]
Can you check if  the contents of your .asoundrc file and asound.conf file are the same? These seem like portaudio issues. this should not prevent the generation of sampletest.sh  file.

**Comment by Shane-Lester** [comment]
They're identical
```
                                    
pcm.softvol {                       
    type softvol                    
    slave.pcm dmix                  
    control {                       
        name Master                 
        card 0                      
    }                               
}                                   
                                    
pcm.micboost {                      
    type route                      
    slave.pcm dsnoop                
    ttable {                        
        0.0 30.0                    
        1.1 30.0                    
    }                               
}                                   
                                    
pcm.!default {                      
    type asym                       
    playback.pcm "plug:softvol"     
    capture.pcm "plug:micboost"     
}                                   
                                    
ctl.!default {                      
    type hw                         
    card 0                          
}                                   
                                    
                                    
```

**Comment by shivasiddharth** [comment]
In both the files can you remove the 
```
ttable {                        
        0.0 30.0                    
        1.1 30.0                    
    }
```
And then run the tests again?

**Comment by Shane-Lester** [comment]
startsample.sh 
``` 

  cd "/home/pi/Assistants-Pi/Alexa/build/SampleApp/src"

  ./SampleApp "/home/pi/Assistants-Pi/Alexa/build/Integration/AlexaClientSDKConfig.json" "/home/pi/Assistants-Pi/Alexa/third-party/alexa-rpi/models" DEBUG9

```

**Comment by shivasiddharth** [comment]
Cool, if the startsample if generated then the Alexa should work, do not mind the failed tests. Can you run the Startsample script first to authenticate? After running the script, scroll up within the terminal to find the authentication code. 
If you see something like "limited mode" on the terminal, it means that the clientid is wrong. If you see "Alexa is idle" then everything is fine.

**Comment by Shane-Lester** [comment]
I had already removed ttable hadn't yet run the tests but ran ./startsample.sh both with and without sudo
```
$ sudo ./startsample.sh
2018-10-19 17:07:32.235 [  1] I sdkVersion: 1.9.0
configFile /home/pi/Assistants-Pi/Alexa/build/Integration/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2018-10-19 17:07:32.252 [  1] 0 ConfigurationNode:initializeSuccess
2018-10-19 17:07:32.264 [  1] 9 MediaPlayer:createCalled
2018-10-19 17:07:32.309 [  1] E MediaPlayer:setupPipelineFailed:reason=createAudioSinkElementFailed,audioSinkElement=alsasink
2018-10-19 17:07:32.309 [  1] E MediaPlayer:initPlayerFailed:reason=setupPipelineFailed
2018-10-19 17:07:32.309 [  1] 9 MediaPlayer:~MediaPlayerCalled

(SampleApp:22102): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
2018-10-19 17:07:32.310 [  1] 9 MediaPlayer:resetPipeline

(SampleApp:22102): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
2018-10-19 17:07:32.310 [  1] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=SpeakMediaPlayer
2018-10-19 17:07:32.310 [  1] C SampleApplication:Failed to create media player for speech!
2018-10-19 17:07:32.310 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!
```

**Comment by Shane-Lester** [comment]
Running tests without 
```
ttable {                        
        0.0 30.0                    
        1.1 30.0                    
    }
```

**Comment by shivasiddharth** [comment]
> $ sudo ./startsample.sh
2018-10-19 17:07:32.235 [  1] I sdkVersion: 1.9.0
configFile /home/pi/Assistants-Pi/Alexa/build/Integration/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2018-10-19 17:07:32.252 [  1] 0 ConfigurationNode:initializeSuccess
2018-10-19 17:07:32.264 [  1] 9 MediaPlayer:createCalled
2018-10-19 17:07:32.309 [  1] E MediaPlayer:setupPipelineFailed:reason=createAudioSinkElementFailed,audioSinkElement=alsasink
2018-10-19 17:07:32.309 [  1] E MediaPlayer:initPlayerFailed:reason=setupPipelineFailed
2018-10-19 17:07:32.309 [  1] 9 MediaPlayer:~MediaPlayerCalled

(SampleApp:22102): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
2018-10-19 17:07:32.310 [  1] 9 MediaPlayer:resetPipeline

(SampleApp:22102): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
2018-10-19 17:07:32.310 [  1] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=SpeakMediaPlayer
2018-10-19 17:07:32.310 [  1] C SampleApplication:Failed to create media player for speech!
2018-10-19 17:07:32.310 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

Gstreamer plugins are not loading. It could be an issue because of "Lite" version of the OS or paths to the plugins being not mentioned properly. Instead of changing directory can you run using the full path to the file ? 
`sudo /home/pi/Assistants-Pi/Alexa/startsample.sh `

**Comment by shivasiddharth** [comment]
I know it must be difficult, but please can you.? Do not change directory or anything. Just copy paste the commands from readme. I tried almost 4-5 times and at all times, it came out successful. Iam pulling my hair out to find the source of error.

**Comment by Shane-Lester** [comment]
What do you mean don’t change the directory – I’ll have to have to reformat the SD and flash a new image- happy to do this (big fan of Open Source work, happy to be contributing in my small way)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by shivasiddharth** [comment]
Changing directory meaning use of cd /home/pi/Assistants-Pi/Alexa/
This time can you choose custom-aiy-hat option instead of aiy-hat. Both have the same config so it does not matter. In that way you need not install the dow2unix.  Let's see if installation of dos2linux has something to do with the errors. I shall fix the AIY script sometime this weekend.

**Comment by Shane-Lester** [comment]
On it.
Report back either in a couple of hours or tomorrow (depending of wifely tolerances)

**Comment by Shane-Lester** [comment]
```
The following tests FAILED:
        253 - TimeTest.testStringConversion (Failed)
        256 - TimeTest.testTimeConversion (Failed)
        792 - SettingsTest.removeSingleSettingObserverWithCorrectKeyTest (Timeout)
Errors while running CTest
Makefile:116: recipe for target 'test' failed
make: *** [test] Error 8
========================Finished Installing Amazon Alexa========================

```
A bit better.

Able to run start sample but it seems to be stuck  repeatedly Checking for Authorization  (23 at present)

**Comment by shivasiddharth** [comment]
you need to scroll up in the terminal like i mentioned before. You will see a link "amazon.com/code" and followed by a key. You need to Authorize by going into amazon.com/code and then entering the key once thats done, the checking for authorization will stop and you cna start interacting with alexa.

**Comment by Shane-Lester** [comment]
Works!
So it was Raspbian Lite that was the issue all along.

Thanks very much- closing this down

**Comment by shivasiddharth** [comment]
In the /home/pi directory, you will have a file called audiosetup. open that and change the contents to 
"AIY-HAT". this will allow you to use the AIY-HAT's pushbutton LED as indicator for Alexa's listening, speaking activity etc. From next time, you can just run the Alexa.py file.

**Comment by Shane-Lester** [comment]
I put AIY-HAT but I selected custom-aiy-hat in the set up as you suggested earlier. Does this need to be different.

Got an error when trying to run alexa.py
```
sudo python ./Assistants-Pi/Alexa/alexa.py
Traceback (most recent call last):
  File "./Assistants-Pi/Alexa/alexa.py", line 6, in <module>
    from alexaindicator import assistantindicator
  File "/home/pi/Assistants-Pi/Alexa/alexaindicator.py", line 10, in <module>
    import yaml
ImportError: No module named yaml
```

Can this connect to the app or other Echo's etc?

**Comment by Shane-Lester** [comment]
```
$ sudo systemctl status alexa.service
● alexa.service - Companion Service
   Loaded: loaded (/lib/systemd/system/alexa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-10-19 23:41:10 BST; 47s ago
  Process: 463 ExecStart=/usr/bin/python -u /home/__USER__/Assistants-Pi/Alexa/alexa.py (code=exited, status=217/USER)
 Main PID: 463 (code=exited, status=217/USER)

Oct 19 23:41:10 assistPi systemd[1]: alexa.service: Unit entered failed state.
Oct 19 23:41:10 assistPi systemd[1]: alexa.service: Failed with result 'exit-code'.
Oct 19 23:41:10 assistPi systemd[1]: alexa.service: Service hold-off time over, scheduling restart.
Oct 19 23:41:10 assistPi systemd[1]: Stopped Companion Service.
Oct 19 23:41:10 assistPi systemd[1]: alexa.service: Start request repeated too quickly.
Oct 19 23:41:10 assistPi systemd[1]: Failed to start Companion Service.
Oct 19 23:41:10 assistPi systemd[1]: alexa.service: Unit entered failed state.
Oct 19 23:41:10 assistPi systemd[1]: alexa.service: Failed with result 'exit-code'.
```
Service isn't running

**Comment by Shane-Lester** [comment]
Works with 
```
sudo /home/pi/Assistants-Pi/Alexa/startsample.sh
```

**Comment by shivasiddharth** [comment]
open a terminal and install pyyaml using:

```
sudo pip install pyyaml
pip install pyyaml
```
sudo will install it for root users and just the pip will install it for non-root uses.

**Comment by shivasiddharth** [comment]
This will have almost full functionality as your Echo dot. You can see this in the list of Alexa devices in the Alexa app

**Comment by shivasiddharth** [comment]
Feel free to reopen if that did not solve the Issue.

**Comment by Shane-Lester** [comment]
Not quite there
`
$ sudo python ./Assistants-Pi/Alexa/alexa.py
`
Works.
Lights- work.
In Alexa App - I can see it as you mentioned- Brilliant.
But...
Doesn't run the service
```
$ sudo systemctl status alexa.service
● alexa.service - Companion Service
   Loaded: loaded (/lib/systemd/system/alexa.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-10-19 23:59:05 BST; 2min 32s ago
  Process: 447 ExecStart=/usr/bin/python -u /home/__USER__/Assistants-Pi/Alexa/alexa.py (code=exited, status=217/USER)
 Main PID: 447 (code=exited, status=217/USER)

Oct 19 23:59:05 assistPi systemd[1]: alexa.service: Unit entered failed state.
Oct 19 23:59:05 assistPi systemd[1]: alexa.service: Failed with result 'exit-code'.
Oct 19 23:59:05 assistPi systemd[1]: alexa.service: Service hold-off time over, scheduling restart.
Oct 19 23:59:05 assistPi systemd[1]: Stopped Companion Service.
Oct 19 23:59:05 assistPi systemd[1]: alexa.service: Start request repeated too quickly.
Oct 19 23:59:05 assistPi systemd[1]: Failed to start Companion Service.
Oct 19 23:59:05 assistPi systemd[1]: alexa.service: Unit entered failed state.
Oct 19 23:59:05 assistPi systemd[1]: alexa.service: Failed with result 'exit-code'.
```
So need to manually start it up (currently using TMUX and disconnecting)

**Comment by shivasiddharth** [comment]
try the following:
```
sudo systemctl stop alexa.service
```
`python -u /home/pi/Assistants-Pi/Alexa/alexa.py`

note that previous command is without sudo. Hopefully that should throw out the errors.

**Comment by Shane-Lester** [comment]
No errors - starts up fine

**Comment by shivasiddharth** [comment]
Ok, let me go through the service and getback.

**Comment by Shane-Lester** [comment]
Will check in tomorrw. Thanks for your help

**Comment by Shane-Lester** [comment]
Any news?

**Comment by shivasiddharth** [comment]
Was away on a personal agenda, never got time to test. Will do it over this weekend.

**Comment by cnoorman** [comment]
Error: Main PID: 447 (code=exited, status=217/USER) is caused by this [issue](https://github.com/shivasiddharth/GassistPi/issues/607#issue-375429734).
Replace `__USER__ `by `pi` in `alexa.service` (pi or whatever username you may use).
This file is most likely in `/lib/systemd/system/`
Type:
```
sudo systemctl daemon-restart
sudo systemctl start alexa.service
```
and it should be ok.

**Comment by nileshlog** [comment]
I get the following error and not able to move ahead

> sudo /home/pi/Assistants-Pi/scripts/installer.sh >>test.txt

`/usr/bin/ld: CMakeFiles/SampleApp.dir/SampleApplication.cpp.o: in function `std::__atomic_base<unsigned long long>::operator=(unsigned long long)':
/usr/include/c++/8/bits/atomic_base.h:374: undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Writer::write(void const*, unsigned int, std::chrono::duration<long long, std::ratio<1ll, 1000ll> >)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Writer::Writer(alexaClientSDK::avsCommon::utils::sds::WriterPolicy, std::shared_ptr<alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::BufferLayout>)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `std::__atomic_base<unsigned long long>::operator unsigned long long() const':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../KWD/src/libKWD.so: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[3]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/build.make:268: SampleApp/src/SampleApp] Error 1
make[2]: *** [CMakeFiles/Makefile2:8758: SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:8770: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:2229: SampleApp] Error 2
chmod: cannot access './test.sh': No such file or directory
chmod: cannot access './startsample.sh': No such file or directory
sudo: ./test.sh: command not found
`

**Comment by Helmi0706** [comment]
> test.sh and startsample.sh will be created by the Alexa installer only if the compilation went through successfully. Looks like there was some issue in compilation. Are you using the latest version of the Raspbian Stretch OS ?

I'm using Raspbian GNU/Linux 10 (buster) and installation of Alexa is successfully. But the file startsample.sh is doesn't exist in folder: /home/pi/Assistants-Pi/Alexa.

> You have chosen to install Alexa
> 
> Installing Amazon Alexa..........
> 
> This script must run as pi, trying to change user...
> This could take a while grab a coffee or beer.........
> Config json file not found!
> Usage: setup.sh <config-json-file> [OPTIONS]
> The <config-json-file> can be downloaded from developer portal and must contain the following:
   "clientId": "<OAuth client ID>"
   "productId": "<your product name for device>"

> Optional parameters
  -s <serial-number>  If nothing is provided, the default device serial number is 123456
  -a <file-name>      The file that contains Android installation configurations (e.g. androidConfig.txt)
  -d <description>    The description of the device.
  -m <manufacturer>   The device manufacturer name.
  -h                  Display this help and exit

> Finished installing Alexa..........

**Comment by shivasiddharth** [comment]
@Helmi0706  Did you place the config file as I have mentioned in the README ?

**Comment by Helmi0706** [comment]
Not yet sir. But now i had a new problem sir, i was place the config on
/home/pi/Assistants-Pi/Alexa and I run that program again. I'm stack on
this process "sudo /home/pi/Assistants-Pi/scripts/installer.sh", I was
waiting for 2 hours and this process not working.
[image: error.JPG]
