### ISSUE TITLE
Play music from YouTube 

### ISSUE THREAD

**Issue by pri-coder** [shivasiddharth/Assistants-Pi#8]
Is there an option to enable playing music from YouTube on a voice command with this install?

**Comment by shivasiddharth** [comment]
Here is all that you can do:

1. Voice control of GPIOs without IFTTT, api.ai, Actions SDK.
2. Voice control of NodeMCU without IFTTT and MQTT.
3. Radio streaming.
4. Voice control of servo connected to RPi GPIO.
5. Safe shutdown RPi using voice command.
6. Stream Music from YouTube.

But these are restricted to Google assistant alone. Amazon did not give me permission to customize Alexa. .. For more details on how the commands work, please visit this page. https://github.com/shivasiddharth/GassistPi

**Comment by pri-coder** [comment]
Ok. Do I need to install GassistPi or can I make the config changes to the Assistants-Pi project?

**Comment by shivasiddharth** [comment]
This installation uses GassistPi only. So there is nothing you need to do. Everything is already done and is ready to be used.

**Comment by pri-coder** [comment]
Oh ok. Do I need to enable anything to make the Play voice command work?

**Comment by pri-coder** [comment]
Saying Play based in your example doesn't play anything from YouTube. It just plays a 2 second music sample.

**Comment by shivasiddharth** [comment]
Ok, my mistake. I had forgotten to change a line  in the installation script here. I have fixed it now.  Open a terminal and type:
`mpsyt set player vlc, set playerargs ,exit`
now the play command should work fine.

**Comment by pri-coder** [comment]
Ran these commands but the play command still does not work

**Comment by shivasiddharth** [comment]
Open the actions.py file which in /home/pi/GassistPi/src directory.  Scroll to` def YouTube(phrase):` and within that down below, you will have a line `playshell.stdin.write(bytes('/' + track + '\n1\n'))` replace that with `playshell.stdin.write(bytes('/' + track + '\n1\n','utf-8'))`

An oversight which had forgotten to correct.

**Comment by pri-coder** [comment]
I have the Assistants Pi code base which does not have an src folder

**Comment by pri-coder** [comment]
Found the GassistPi in home/Pi as well and made the changes you suggested. Play command now works. Thanks!
