### ISSUE TITLE
Unable to play music from Deezer

### ISSUE THREAD

**Issue by rutherb** [shivasiddharth/Assistants-Pi#81]
Hi - followed the instructions to set up Deezer account and update API and config.yaml but on running Google Assistant and asking it to play playlist number 1 from Deezer I get the errors below, Google Assistant is working OK for normal questions e.g. time, weather etc.:-

stopping vlc
/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ERROR:__main__:'data'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 666, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 658, in main
    deezer_playlist_select(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1495, in deezer_playlist_select
    if deezer_user_playlist_info['data'] != []:
KeyError: 'data'

**Comment by shivasiddharth** [comment]
Check https://github.com/shivasiddharth/GassistPi/issues/554
