### ISSUE TITLE
Google assistant sometimes starts to hotword Alexa

### ISSUE THREAD

**Issue by williamhemmingsen** [shivasiddharth/Assistants-Pi#91]
Sometimes when saying Alexa, both alexa and google respond at same time.  Any idea why this is?  and how to correct?

**Comment by shivasiddharth** [comment]
In google assistant, custom wakeword is enabled by default and one of the custom wakeword is Alexa. Go into /home/pi/GassistPi/src/config.yaml and set Custom wakeword option to `"Disabled"`

**Comment by williamhemmingsen** [comment]
doh, sorry thanks that fixed.
