### ISSUE TITLE
ImportError: No module named 'kodijson'

### ISSUE THREAD

**Issue by HariniRao19** [shivasiddharth/Assistants-Pi#96]
/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id 'Model id'

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 18, in <module>
    from kodijson import Kodi, PLAYER_VIDEO
ImportError: No module named 'kodijson'

pls tell me the problem ASAP..

**Comment by shivasiddharth** [comment]
You have not installed the google assistant, but trying to run the assistant's scripts.

**Comment by HariniRao19** [comment]
Thank you

**Comment by batool-1** [comment]
> Thank you

 i m facing the same problem ...  google assistant is already installed
