### ISSUE TITLE
Alexa fails to install

### ISSUE THREAD

**Issue by jmfrancofraiz** [shivasiddharth/Assistants-Pi#98]
I have a Pi 3 Model B, with an AIY-HAT. Fresh install of Raspbian Stretch Lite. The first problem I encoutered said 'pip command not found', so I had to manually install it with 'sudo apt-get install python-pip'. After that, Alexa built OK but failed at tests:

```
The following tests FAILED:
	253 - TimeTest.testStringConversion (Failed)
	256 - TimeTest.testTimeConversion (Failed)
	846 - MediaPlayerTest.testStartPlayWaitForEnd (Failed)
	847 - MediaPlayerTest.testStartPlayForUrl (Failed)
	848 - MediaPlayerTest.testConsecutiveSetSource (Failed)
	849 - MediaPlayerTest.testStartPlayWaitForEndStartPlayAgain (Failed)
	850 - MediaPlayerTest.testStopPlay (Failed)
	851 - MediaPlayerTest.testStartPlayCallAfterStopPlay (Failed)
	852 - MediaPlayerTest.testStartPlayCallAfterStopPlayDifferentSource (Failed)
	853 - MediaPlayerTest.testPauseDuringPlay (Failed)
	854 - MediaPlayerTest.testResumeAfterPauseThenStop (Failed)
	855 - MediaPlayerTest.testStopAfterPause (Failed)
	856 - MediaPlayerTest.testPauseAfterPause (Failed)
	857 - MediaPlayerTest.testResumeAfterPlay (Failed)
	858 - MediaPlayerTest.testGetOffsetInMilliseconds (Failed)
	860 - MediaPlayerTest.testGetOffsetWhenStoppedFails (Failed)
	861 - MediaPlayerTest.testGetOffsetWhenPaused (Failed)
	862 - MediaPlayerTest.testPlayingTwoAttachments (Failed)
	863 - MediaPlayerTest.testUnsteadyReads (Failed)
	864 - MediaPlayerTest.testRecoveryFromPausedReads (Failed)
	865 - MediaPlayerTest.testStartPlayWithUrlPlaylistWaitForEnd (Failed)
	866 - MediaPlayerTest.testSetOffsetSeekableSource (Failed)
	869 - MediaPlayerTest.testRepeatAttachment (Failed)
	870 - MediaPlayerTest.testSetVolumePlays (Failed)
	871 - MediaPlayerTest.testAdjustVolumePlaysDuringPlay (Failed)
	872 - MediaPlayerTest.testAdjustVolumePlays (Failed)
	873 - MediaPlayerTest.testAdjustVolumeOutOfBounds (Failed)
	874 - MediaPlayerTest.testSetMutePlays (Failed)
	877 - MediaPlayerTest.testReadTags (Failed)
	878 - MediaPlayerTest.testConsecutiveSameApiCalls (Failed)
	879 - MediaPlayerTest.testImmediatePause (Failed)
	880 - MediaPlayerTest.multiplePlayAndSetSource (Failed)
	882 - MediaPlayerTest.doublePause (Failed)
	883 - MediaPlayerTest.resumeWhenPlaying (Failed)
	884 - MediaPlayerTest.resumeWhenStopped (Failed)
	885 - MediaPlayerTest.newSetSourceLeadsToStoppedCallback (Failed)
	886 - MediaPlayerTest.resumeAfterPauseWithPendingPlay (Failed)
Errors while running CTest
Makefile:116: fallo en las instrucciones para el objetivo 'test'
make: *** [test] Error 8
```

**Comment by shivasiddharth** [comment]
Are you using Raspbian Lite version ? If yes, then please switch to Raspbian desktop.

**Comment by jatt01ankit** [comment]
Please help me with these errors.......
The following tests FAILED:
        846 - MediaPlayerTest.testStartPlayWaitForEnd (Failed)
        847 - MediaPlayerTest.testStartPlayForUrl (Failed)
        848 - MediaPlayerTest.testConsecutiveSetSource (Failed)
        849 - MediaPlayerTest.testStartPlayWaitForEndStartPlayAgain (Failed)
        854 - MediaPlayerTest.testResumeAfterPauseThenStop (Failed)
        862 - MediaPlayerTest.testPlayingTwoAttachments (Failed)
        863 - MediaPlayerTest.testUnsteadyReads (Failed)
        864 - MediaPlayerTest.testRecoveryFromPausedReads (Failed)
        865 - MediaPlayerTest.testStartPlayWithUrlPlaylistWaitForEnd (Failed)
        866 - MediaPlayerTest.testSetOffsetSeekableSource (Failed)
        869 - MediaPlayerTest.testRepeatAttachment (Failed)
        870 - MediaPlayerTest.testSetVolumePlays (Failed)
        871 - MediaPlayerTest.testAdjustVolumePlaysDuringPlay (Failed)
        872 - MediaPlayerTest.testAdjustVolumePlays (Failed)
        873 - MediaPlayerTest.testAdjustVolumeOutOfBounds (Failed)
        874 - MediaPlayerTest.testSetMutePlays (Failed)
        877 - MediaPlayerTest.testReadTags (Failed)
        879 - MediaPlayerTest.testImmediatePause (Failed)
        880 - MediaPlayerTest.multiplePlayAndSetSource (Failed)
        886 - MediaPlayerTest.resumeAfterPauseWithPendingPlay (Failed)
Errors while running CTest
Makefile:116: recipe for target 'test' failed
make: *** [test] Error 8
thank you so much in advance.....

**Comment by jatt01ankit** [comment]
> Please help me with these errors.......
> The following tests FAILED:
> 846 - MediaPlayerTest.testStartPlayWaitForEnd (Failed)
> 847 - MediaPlayerTest.testStartPlayForUrl (Failed)
> 848 - MediaPlayerTest.testConsecutiveSetSource (Failed)
> 849 - MediaPlayerTest.testStartPlayWaitForEndStartPlayAgain (Failed)
> 854 - MediaPlayerTest.testResumeAfterPauseThenStop (Failed)
> 862 - MediaPlayerTest.testPlayingTwoAttachments (Failed)
> 863 - MediaPlayerTest.testUnsteadyReads (Failed)
> 864 - MediaPlayerTest.testRecoveryFromPausedReads (Failed)
> 865 - MediaPlayerTest.testStartPlayWithUrlPlaylistWaitForEnd (Failed)
> 866 - MediaPlayerTest.testSetOffsetSeekableSource (Failed)
> 869 - MediaPlayerTest.testRepeatAttachment (Failed)
> 870 - MediaPlayerTest.testSetVolumePlays (Failed)
> 871 - MediaPlayerTest.testAdjustVolumePlaysDuringPlay (Failed)
> 872 - MediaPlayerTest.testAdjustVolumePlays (Failed)
> 873 - MediaPlayerTest.testAdjustVolumeOutOfBounds (Failed)
> 874 - MediaPlayerTest.testSetMutePlays (Failed)
> 877 - MediaPlayerTest.testReadTags (Failed)
> 879 - MediaPlayerTest.testImmediatePause (Failed)
> 880 - MediaPlayerTest.multiplePlayAndSetSource (Failed)
> 886 - MediaPlayerTest.resumeAfterPauseWithPendingPlay (Failed)
> Errors while running CTest
> Makefile:116: recipe for target 'test' failed
> make: *** [test] Error 8
> thank you so much in advance.....

I'm using Raspbean desktop stretch
